# Generated by Django 4.1.7 on 2023-03-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heavens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
