# Generated by Django 4.1.7 on 2023-03-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heavens', '0003_entity_abs_mag_entity_app_mag_entity_ly_dist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('ra', models.CharField(max_length=50)),
                ('dec', models.CharField(max_length=50)),
                ('spec_class', models.CharField(max_length=50)),
                ('abs_mag', models.CharField(max_length=50)),
                ('app_mag', models.CharField(max_length=50)),
                ('ly_dist', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeteorShower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('ra', models.CharField(max_length=50)),
                ('dec', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ra', models.CharField(max_length=50)),
                ('dec', models.CharField(max_length=50)),
                ('spec_class', models.CharField(max_length=50)),
                ('abs_mag', models.CharField(max_length=50)),
                ('app_mag', models.CharField(max_length=50)),
                ('ly_dist', models.CharField(max_length=50)),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heavens.constellation')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ra', models.CharField(max_length=50)),
                ('dec', models.CharField(max_length=50)),
                ('spec_class', models.CharField(max_length=50)),
                ('abs_mag', models.CharField(max_length=50)),
                ('app_mag', models.CharField(max_length=50)),
                ('ly_dist', models.CharField(max_length=50)),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heavens.constellation')),
            ],
        ),
    ]
