# Generated by Django 4.1.7 on 2023-03-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heavens', '0007_alter_meteorshower_date_alter_meteorshower_dec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteorshower',
            name='dec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meteorshower',
            name='ra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
