# Generated by Django 4.1.7 on 2023-03-09 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_plan_creator_plan_notes_plan_title_plan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='creator',
        ),
        migrations.AddField(
            model_name='plan',
            name='event',
            field=models.CharField(choices=[('strgz', 'Star gazing'), ('mtshr', 'Meteor Shower'), ('comet', 'Comet sighting'), ('plntv', 'Planet viewing'), ('hcrft', 'Human Craft')], default='strgz', max_length=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
