# Generated by Django 4.1.7 on 2023-03-10 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_plan_creator_plan_event_alter_plan_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_zip',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
