# Generated by Django 4.1.7 on 2023-03-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_default_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_zip',
        ),
        migrations.AddField(
            model_name='user',
            name='zip_test',
            field=models.CharField(default='29601', max_length=10),
        ),
    ]
