# Generated by Django 4.1.7 on 2023-03-11 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_default_zip_user_zip_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='zip_test',
        ),
        migrations.AddField(
            model_name='profile',
            name='default_zip',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
