# Generated by Django 4.1.7 on 2023-03-14 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_zip_test_profile_default_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='default_zip',
        ),
        migrations.AddField(
            model_name='user',
            name='default_zip',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
