# Generated by Django 4.1.7 on 2023-03-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heavens', '0004_comet_constellation_meteorshower_star_planet'),
        ('accounts', '0012_user_tracked_comets_user_tracked_constellations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tracked_comets',
            field=models.ManyToManyField(related_name='Comet+', to='heavens.comet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tracked_constellations',
            field=models.ManyToManyField(related_name='Constellation+', to='heavens.constellation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tracked_meteor_showers',
            field=models.ManyToManyField(related_name='MeteorShower+', to='heavens.meteorshower'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tracked_planets',
            field=models.ManyToManyField(related_name='Planet+', to='heavens.planet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tracked_stars',
            field=models.ManyToManyField(related_name='Star+', to='heavens.star'),
        ),
    ]
