# Generated by Django 4.1.7 on 2023-03-15 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heavens', '0004_comet_constellation_meteorshower_star_planet'),
        ('accounts', '0013_alter_user_tracked_comets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tracked_comets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tracked_constellations',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tracked_meteor_showers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tracked_planets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tracked_stars',
        ),
        migrations.AddField(
            model_name='user',
            name='tracked_stars',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heavens.star'),
        ),
    ]
