# Generated by Django 4.1.7 on 2023-03-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heavens', '0004_comet_constellation_meteorshower_star_planet'),
        ('accounts', '0014_remove_user_tracked_comets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tracked_stars',
        ),
        migrations.AddField(
            model_name='user',
            name='tracked_constellations',
            field=models.ManyToManyField(related_name='+', to='heavens.constellation'),
        ),
    ]
