# Generated by Django 4.1.7 on 2023-03-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heavens', '0004_comet_constellation_meteorshower_star_planet'),
        ('accounts', '0015_remove_user_tracked_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tracked_constellations',
            field=models.ManyToManyField(null=True, related_name='+', to='heavens.constellation'),
        ),
    ]
