# Generated by Django 4.1.7 on 2023-03-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heavens', '0008_alter_meteorshower_dec_alter_meteorshower_ra'),
        ('accounts', '0016_alter_user_tracked_constellations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tracked_comets',
            field=models.ManyToManyField(related_name='users', to='heavens.comet'),
        ),
        migrations.AddField(
            model_name='user',
            name='tracked_meteor_showers',
            field=models.ManyToManyField(related_name='users', to='heavens.meteorshower'),
        ),
        migrations.AddField(
            model_name='user',
            name='tracked_planets',
            field=models.ManyToManyField(related_name='users', to='heavens.planet'),
        ),
        migrations.AddField(
            model_name='user',
            name='tracked_stars',
            field=models.ManyToManyField(related_name='users', to='heavens.star'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tracked_constellations',
            field=models.ManyToManyField(related_name='users', to='heavens.constellation'),
        ),
    ]
