# Generated by Django 4.1.7 on 2023-03-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_user_default_zip_profile_default_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='default_zip',
        ),
        migrations.AddField(
            model_name='user',
            name='default_zip',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
