# Generated by Django 4.1.7 on 2023-03-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_profile_default_zip_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_zip',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
